'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/components/providers/AuthProvider';

type Case = { id: string; memberRefToken: string; payerRef: string; procedureCode: string; diagnosisCode: string; status: string; version: number; urgency: string; dueAt: string; ownerId: string; clinicalReviewerId?: string; policyVersion?: string; payerReceipt?: string; acceptanceCriteria: Array<{ code: string; description: string; required: boolean }> };
type Detail = { case: Case & { payload: Record<string, unknown> }; evidence: Array<Record<string, any>>; events: Array<Record<string, any>> };
const transitions: Record<string, string[]> = { intake: ['evidence_review'], evidence_review: ['clinical_review', 'needs_information'], needs_information: ['evidence_review'], clinical_review: ['submission_ready', 'needs_information', 'denied_internal'], submission_ready: ['submission_queued'], payer_error: ['submission_queued'], denied: ['appeal_review', 'closed'], appeal_review: ['appeal_ready', 'closed'], appeal_ready: ['appeal_queued'], approved: ['closed'] };

async function jsonRequest(path: string, options?: RequestInit) {
  const response = await fetch(path, { ...options, headers: { 'content-type': 'application/json', ...(options?.headers || {}) }, cache: 'no-store' });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || 'Request failed');
  return body;
}

export default function GovernedPriorAuthWorkspace() {
  const { user } = useAuth();
  const [cases, setCases] = useState<Case[]>([]);
  const [selected, setSelected] = useState('');
  const [detail, setDetail] = useState<Detail | null>(null);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  const [reason, setReason] = useState('Reviewed workflow evidence and documented the operational decision.');
  const [form, setForm] = useState({ memberRef: '', payerRef: '', procedureCode: '', diagnosisCode: '', requestedBy: '', urgency: 'standard', criterionCode: '', criterionDescription: '' });
  const [evidence, setEvidence] = useState({ evidenceCode: '', evidenceType: 'clinical_note', uri: '', sourceSystem: 'fhir', version: 'R4', effectiveAt: '', contentDigest: '' });
  const [policy, setPolicy] = useState({ payerRef: '', procedureCode: '', version: '', sourceUri: '', effectiveAt: '', code: '', description: '' });

  const load = useCallback(async () => { const data = await jsonRequest('/api/governed/prior-auth'); setCases(data.cases); setSelected((current: string) => current || data.cases[0]?.id || ''); }, []);
  const loadDetail = useCallback(async (id: string) => { if (id) setDetail(await jsonRequest(`/api/governed/prior-auth?id=${encodeURIComponent(id)}`)); else setDetail(null); }, []);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  useEffect(() => { loadDetail(selected).catch((e) => setError(e.message)); }, [loadDetail, selected]);

  async function run(action: () => Promise<unknown>, message: string) { setBusy(true); setError(''); setNotice(''); try { await action(); setNotice(message); await load(); if (selected) await loadDetail(selected); } catch (e) { setError(e instanceof Error ? e.message : 'Request failed'); } finally { setBusy(false); } }
  const createCase = () => run(async () => { const result = await jsonRequest('/api/governed/prior-auth', { method: 'POST', headers: { 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify({ ...form, dueAt: new Date(Date.now() + (form.urgency === 'urgent' ? 86400000 : 5 * 86400000)).toISOString(), acceptanceCriteria: [{ code: form.criterionCode, description: form.criterionDescription, required: true }] }) }); setSelected(result.case.id); }, 'Case persisted and intake event audited.');
  const addEvidence = () => run(() => jsonRequest('/api/governed/prior-auth/evidence', { method: 'POST', body: JSON.stringify({ caseId: selected, evidence: { ...evidence, effectiveAt: new Date(evidence.effectiveAt).toISOString() } }) }), 'Evidence provenance encrypted and attached.');
  const transition = (toStatus: string) => run(() => jsonRequest('/api/governed/prior-auth', { method: 'PATCH', body: JSON.stringify({ caseId: detail?.case.id, expectedVersion: detail?.case.version, toStatus, reason, attestation: ['submission_ready', 'appeal_ready'].includes(toStatus) }) }), `Case moved to ${toStatus.replace(/_/g, ' ')}.`);
  const savePolicy = () => run(() => jsonRequest('/api/governed/prior-auth', { method: 'PUT', body: JSON.stringify({ payerRef: policy.payerRef, procedureCode: policy.procedureCode, version: policy.version, sourceUri: policy.sourceUri, effectiveAt: new Date(policy.effectiveAt).toISOString(), rules: [{ code: policy.code, description: policy.description, required: true }] }) }), 'Versioned payer policy saved.');
  const availableTransitions = useMemo(() => transitions[detail?.case.status || ''] || [], [detail?.case.status]);

  return <div className="stack">
    {error ? <div className="card" style={{ color: '#b91c1c' }}>{error}</div> : null}{notice ? <div className="card" style={{ color: '#166534' }}>{notice}</div> : null}
    {['analyst', 'admin'].includes(user?.role || '') ? <div className="card stack"><h3>New authorization intake</h3><div className="grid columns-4"><input placeholder="Member reference" value={form.memberRef} onChange={(e) => setForm({ ...form, memberRef: e.target.value })} /><input placeholder="Payer reference" value={form.payerRef} onChange={(e) => setForm({ ...form, payerRef: e.target.value })} /><input placeholder="CPT/HCPCS" value={form.procedureCode} onChange={(e) => setForm({ ...form, procedureCode: e.target.value })} /><input placeholder="ICD-10" value={form.diagnosisCode} onChange={(e) => setForm({ ...form, diagnosisCode: e.target.value })} /><input placeholder="Requesting provider" value={form.requestedBy} onChange={(e) => setForm({ ...form, requestedBy: e.target.value })} /><select value={form.urgency} onChange={(e) => setForm({ ...form, urgency: e.target.value })}><option value="standard">Standard</option><option value="urgent">Urgent</option></select><input placeholder="Required evidence code" value={form.criterionCode} onChange={(e) => setForm({ ...form, criterionCode: e.target.value })} /><input placeholder="Criterion description" value={form.criterionDescription} onChange={(e) => setForm({ ...form, criterionDescription: e.target.value })} /></div><button className="button primary" disabled={busy} onClick={createCase}>Create case</button></div> : null}
    {user?.role === 'admin' ? <div className="card stack"><h3>Versioned payer policy</h3><div className="grid columns-4"><input placeholder="Payer" value={policy.payerRef} onChange={(e) => setPolicy({ ...policy, payerRef: e.target.value })} /><input placeholder="Procedure code" value={policy.procedureCode} onChange={(e) => setPolicy({ ...policy, procedureCode: e.target.value })} /><input placeholder="Policy version" value={policy.version} onChange={(e) => setPolicy({ ...policy, version: e.target.value })} /><input placeholder="Source URI" value={policy.sourceUri} onChange={(e) => setPolicy({ ...policy, sourceUri: e.target.value })} /><input type="datetime-local" value={policy.effectiveAt} onChange={(e) => setPolicy({ ...policy, effectiveAt: e.target.value })} /><input placeholder="Evidence code" value={policy.code} onChange={(e) => setPolicy({ ...policy, code: e.target.value })} /><input placeholder="Rule description" value={policy.description} onChange={(e) => setPolicy({ ...policy, description: e.target.value })} /></div><button className="button primary" disabled={busy} onClick={savePolicy}>Save policy version</button></div> : null}
    <div className="grid columns-2"><div className="card"><div className="section-head"><h3>Tenant case queue</h3><span className="status-chip">{cases.length} cases</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Member token</th><th>Codes</th><th>Status</th><th>Due</th></tr></thead><tbody>{cases.map((item) => <tr key={item.id} onClick={() => setSelected(item.id)} style={{ cursor: 'pointer', background: item.id === selected ? '#eff6ff' : undefined }}><td>{item.memberRefToken}</td><td>{item.procedureCode}<br />{item.diagnosisCode}</td><td><span className="status-chip">{item.status.replace(/_/g, ' ')}</span></td><td>{new Date(item.dueAt).toLocaleString()}</td></tr>)}</tbody></table></div></div>
    <div className="card stack"><h3>Case control</h3>{detail ? <><div className="detail-field-grid"><div className="detail-field"><span>Case</span><div>{detail.case.id}</div></div><div className="detail-field"><span>Version</span><div>{detail.case.version}</div></div><div className="detail-field"><span>Payer</span><div>{detail.case.payerRef}</div></div><div className="detail-field"><span>Policy</span><div>{detail.case.policyVersion || 'Not reviewed'}</div></div><div className="detail-field"><span>Payer receipt</span><div>{detail.case.payerReceipt || 'Not submitted'}</div></div></div><label>Decision rationale<textarea rows={3} value={reason} onChange={(e) => setReason(e.target.value)} /></label><div className="button-row">{availableTransitions.map((next) => <button key={next} className="button primary" disabled={busy} onClick={() => transition(next)}>{next.replace(/_/g, ' ')}</button>)}</div></> : <div className="muted">Select a case.</div>}</div></div>
    {detail && ['evidence_review', 'needs_information', 'clinical_review'].includes(detail.case.status) && ['analyst', 'clinician', 'admin'].includes(user?.role || '') ? <div className="card stack"><h3>Add validated evidence</h3><div className="grid columns-4"><input placeholder="Evidence code" value={evidence.evidenceCode} onChange={(e) => setEvidence({ ...evidence, evidenceCode: e.target.value })} /><input placeholder="Evidence type" value={evidence.evidenceType} onChange={(e) => setEvidence({ ...evidence, evidenceType: e.target.value })} /><input placeholder="HTTPS or URN source" value={evidence.uri} onChange={(e) => setEvidence({ ...evidence, uri: e.target.value })} /><select value={evidence.sourceSystem} onChange={(e) => setEvidence({ ...evidence, sourceSystem: e.target.value })}><option value="fhir">FHIR</option><option value="document_store">Document store</option></select><input placeholder="Source version" value={evidence.version} onChange={(e) => setEvidence({ ...evidence, version: e.target.value })} /><input type="datetime-local" value={evidence.effectiveAt} onChange={(e) => setEvidence({ ...evidence, effectiveAt: e.target.value })} /><input placeholder="SHA-256 content digest" value={evidence.contentDigest} onChange={(e) => setEvidence({ ...evidence, contentDigest: e.target.value })} /></div><button className="button primary" disabled={busy} onClick={addEvidence}>Attach evidence</button></div> : null}
    {detail ? <div className="grid columns-2"><div className="card"><h3>Evidence</h3><ul className="feature-list">{detail.evidence.map((item) => <li key={item.id}><strong>{item.evidence_code}</strong> · {item.source_system} {item.source_version}<br /><span className="muted">{item.content_digest}</span></li>)}</ul></div><div className="card"><h3>Immutable history</h3><ul className="feature-list">{detail.events.map((item, index) => <li key={index}><strong>{item.event_type}</strong> · {item.from_status || 'new'} → {item.to_status}<br /><span className="muted">{item.actor_role} · {new Date(item.occurred_at).toLocaleString()} · {item.reason || ''}</span></li>)}</ul></div></div> : null}
  </div>;
}
